def keystorePropertiesFile = rootProject.file("android/manufacturers/stone/ingenico/ingenico-keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    productFlavors {
        ingenico {
            dimension "model"
            signingConfig signingConfigs.debug
            versionNameSuffix "-ingenico"
        }
    }
}